from enum import Enum


class ShiftTypesApiEnum(Enum):
    MORNING = "MORNING"
    MORNING_BACKUP = "MORNING_BACKUP"
    EVENING = "EVENING"
    CLOSING = "CLOSING"
    THURSDAY_BACKUP = "THURSDAY_BACKUP"
    WEEKEND_MORNING = "WEEKEND_MORNING"
    WEEKEND_MORNING_BACKUP = "WEEKEND_MORNING_BACKUP"
    WEEKEND_EVENING_BACKUP = "WEEKEND_EVENING_BACKUP"
    STAND_BY = "STAND_BY"
