name: Build and publish npm package

on:
  push:
    branches:
      - master
      - feature/create_fastapi_server

jobs:
  generate-npm-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login docker github
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          echo $GITHUB_ACTOR
          echo $GH_TOKEN | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: employee_schedule_server:latest

      - name: Generate build and publish npm package
        run: |
          
          docker run -it --rm employee_schedule_server:latest python ./generate_openapi.py > openapi.json

          npx @openapitools/openapi-generator-cli generate -i "openapi.json" \
          -g typescript-axios --additional-properties=npmName=@noadudai/EmployeesScheduleClient \
          --additional-properties=npmVersion=${{github.sha}} \
          --additional-properties=useSingleRequestParameter=true -o ./api-npm
          cd api-npm/
          
          apt get jq -y
          
          jq '.repository.url = "https://github.com/noadudai/EmployeeShiftsSchedule"' package.json 
          
          npm install 
          npm run build
          
          npm set "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN"
          npm publish
