name: Build and publish npm package

on:
  push:
    branches:
      - master
      - feature/create_fastapi_server

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  generate-npm-package:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Login docker github
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          echo $GITHUB_ACTOR
          echo $GH_TOKEN | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate build and publish npm package
        run: |
          
          SHORTSHA=${{github.sha}}
          REG_SHA=$(echo $(SHORTSHA::5) | sed -E 's/(.)(..)(.*)/\1.\2.\3/')
          echo REG_SHA
          sudo apt-get update
          sudo apt-get install jq -y
          
          docker run --rm ${{ steps.meta.outputs.tags }} python ./generate_openapi.py > openapi.json

          
          npx @openapitools/openapi-generator-cli generate -i "openapi.json" \
          -g typescript-axios --additional-properties=npmName=@noadudai/EmployeesScheduleClient \
          --additional-properties=npmVersion=${SHORTSHA::5} \
          --additional-properties=useSingleRequestParameter=true -o ./api-npm
          cd api-npm/

          jq '.repository.url = "https://github.com/noadudai/EmployeeShiftsSchedule"' package.json 
          cat package.json 
          
          npm install 
          npm run build
          
          npm set "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN"
          npm publish
